spring:
  application:
    name: IdentityServer

  datasource:
    url: jdbc:postgresql://localhost:5432/skillsharedb
    username: shubhamjain
    password: none
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

jwt:
  secret: VHKJMNnbfhbsjkdbVJHVkhbJBKJBsmfnbngygiyguFYVHJbkjnjnsjdnlkfn
  expiration: 600000 # 10 mins token expiration time

server:
  port: 8088